### ISSUE TITLE
Refactor modules based on the proposed schema

### ISSUE THREAD

**Issue by marcelobianchi** [endarthur/autti#7]
After an afternoon of discussion we came to the proposed solution for the autti schema of modules. Should be implemented

[TIPAGEM.txt](https://github.com/endarthur/autti/files/1201716/TIPAGEM.txt)

**Comment by endarthur** [comment]
Finished refactoring code and example notebook. Used single underscore (_) instead of double underscore (__) on non public methods and attributes to avoid name mangling, as suggested in pep 8:
https://www.python.org/dev/peps/pep-0008/#id47
