### ISSUE TITLE
Datamodel to_auttitude() method is set as parameter

### ISSUE THREAD

**Issue by marcelobianchi** [endarthur/autti#8]
Since the method **to_auttitude()** is set as property better to rename it to **auttitude()** only. Acessing a property don't really have the idea to ask for the object to do something. Better to remove the verb.

**Comment by endarthur** [comment]
Changed. Following that line, all the other properties are nouns. Should all the explicit methods of datamodel's classes be changed to include some sort of qualifier? For example, being x and y being instances of Plane,
```
x.angle(y) => x.angle_with(y)
x.cross(y) => x.cross_with(y)
x.great_circle(step) => x.get_great_circle(step)
x.arc(y) => x.arc_to(y)
x.intersect(y) => x.intersection_with(y)
```
And so on. Would make the methods more verbose, though not by much. We discussed something like this last Friday, and now it seems to me that it would make more sense. What do you think?

**Comment by marcelobianchi** [comment]
I do agree on that. Makes things more explicit at least on the first try.
